### PR TITLE
Allow ID as prop

### PR DESCRIPTION
**Pull request by athersharif**
useful to identify an individual switch.

### CODE REVIEW

**Comment by athersharif** [comment]
@pgrimard please review.

**Comment by pgrimard** [comment]
You could achieve the same result by simply using a `ref` attribute on the switch could you not?  Seems to me providing the switch with an `id` opens it up to manipulation outside of a React context.  Maybe I'm just not understanding your use case.

**Comment by athersharif** [comment]
yeah i can understand that - for my use case, having an `id` prop makes life so much easier using this with https://github.com/mozilla-services/react-jsonschema-form.

**Comment by pgrimard** [comment]
Closing this PR because this repo is being archived and will no longer be maintained.

**Pull request closed without merging**
