### PR TITLE
remove call to toggle state internally regardless of on prop

### PR DESCRIPTION
**Pull request by stevokk**
When a user clicks and we want to cancel the toggle, your library toggles the state anyway. This is a bug in our case where the network request to toggle the remote state fails and we're left with an incorrect toggle state.

### CODE REVIEW

**Comment by pgrimard** [comment]
Essentially what you're looking for is to have the switch just be a dump component and manage the `on` state entirely through props and remove the internal state of `on`, correct?

**Comment by stevokk** [comment]
Keeping the state internally and also through props but allowing them to be out of sync isn't a behaviour I think you want to have. Best practice for these small components is to keep them dumb where possible

**Comment by pgrimard** [comment]
Since this is a breaking change, I have released version 3.0.0 to solve your problem.  You should upgrade to that version instead.

**Comment by stevokk** [comment]
Perfect, thanks for getting back to me, will update my code.

**Pull request closed without merging**
