### PR TITLE
Use prop-types rather than React.PropTypes

### PR DESCRIPTION
**Pull request by cjpete**
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

https://github.com/pgrimard/react-toggle-switch/issues/11

### CODE REVIEW

**Comment by pgrimard** [comment]
Hi Chris, thanks for this PR.  Would you mind updating the sample project as well so it remains in sync?

**Comment by cjpete** [comment]
@pgrimard I had a look at the sample project, but the examples don't actually get passed any props, so all I've done is a minor change for consistency.

**Comment by pgrimard** [comment]
Thanks again Chris.  I've merged your PR.

**Comment by pgrimard** [comment]
I've published 2.1.4 to NPM.

**Pull request merged**
